package main

import (
	"bytes"
	"net/http"
	"time"
)

func main() {
	jsonStr := []byte(`{
  "test": "event"
}`)

	req, err := http.NewRequest("POST", "https://eoywrbj6otr1rve.m.pipedream.net", bytes.NewReader(jsonStr))
	req.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: time.Minute}

	resp, err := client.Do(req)

	if err != nil {
		panic(err)
	}

	defer resp.Body.Close()
}
